### ISSUE TITLE
안드로이드 메인 기능 안되는 이슈

### ISSUE THREAD

**Issue by Rayakeem** [LightandSaltt/2024_capstone_design_teamPioneer#3]
hansik_main_page.dart 의 홈페이지 기능 (URL이동)아예 실행 안 됨, 학교맵(네이버지도API) 맵은 열리는데 지도 표시가 안됨

**Comment by LightandSaltt** [comment]
![안드로이드_지도_오류](https://github.com/LightandSaltt/2024_capstone_design_teamPioneer/assets/99009678/20241071-c95d-4b9f-8921-3f5fb91855fa)
안드로이드 환경에서 지도에 들어갔을 때 이 오류가 떴는데, 이 오류에 대해서 좀 찾아봤는데 안드로이드에 클라이언트 ID가 누락된 것 같기도 합니다! AndroidManifest.xml 봐야 할 듯!

![안드로이드_홈페이지연결오류](https://github.com/LightandSaltt/2024_capstone_design_teamPioneer/assets/99009678/3a5fe9d3-fa90-4224-9335-1ff2656c7757)
홈페이지 클릭했을 때 콘솔에 뜨는게 이건데, URL launcher 문제인 것 같은데 자세한 건 더 찾아볼게요!

**Comment by Rayakeem** [comment]
client ID는 잘 적용했는데, 네이버 맵 api SDK 문제였어요! 그래들파일에  implementation("com.naver.maps:map-sdk:3.16.2") 추가 했더니 잘 작동 합니다. 이 이슈는 닫고 url이랑 로그인 이슈는 다시 올리겠습니다 ..
